image: docker:latest
services:
 - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker:2375
  TAG: 0.0.1-SNAPSHOT
  BUILD_DEPENDENCY: target/dependency

stages:
- build
- test
- package
- install

cache:
  paths:
  - ui/node
  - ui/node_modules

chrome:
  image: maven:3-jdk-8
  script:
  before_script:
  - "apt-get -qq -y install wget"
  - "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - "
  - "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'"
  - "apt-get -y update"
  - "apt-get -y install google-chrome-stable"
  artifacts:
    paths:
    - ui/target/*
    - api/target/*
    - gateway/target/*

maven-build:
  extends: chrome
  stage: build
  script: "mvn compile"

maven-test:
  extends: chrome
  stage: test
  script: "mvn test"

docker-build:
  stage: package
  script:
  - docker build --build-arg DEPENDENCY=BUILD_DEPENDENCY -t tenentedan9/ui:TAG ./ui
  - docker build --build-arg DEPENDENCY=BUILD_DEPENDENCY -t tenentedan9/gateway:TAG ./gateway
  - docker build --build-arg DEPENDENCY=BUILD_DEPENDENCY -t tenentedan9/api:TAG ./api

docker-push:
  stage: install
  script:
  - ls
  - docker login -u AWS -p $AWS_TOKEN https://$AWS_DOCKER_REGISTRY/
  - docker tag tenentedan9/ui:$TAG $AWS_DOCKER_REGISTRY/ui:$TAG
  - docker tag tenentedan9/gateway:$TAG $AWS_DOCKER_REGISTRY/gateway:$TAG
  - docker tag tenentedan9/api:$TAG $AWS_DOCKER_REGISTRY/api:$TAG
  - docker push $AWS_DOCKER_REGISTRY/ui:$TAG
  - docker push $AWS_DOCKER_REGISTRY/gateway:$TAG
  - docker push $AWS_DOCKER_REGISTRY/api:$TAG

