image: docker:latest
services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker:2375
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
- build
- test
- package
- install

cache:
  paths:
  - ui/node
  - ui/node_modules
  - .m2/

.chrome_template: &chrome_definition  # Hidden key that defines an anchor named 'job_definition'
  image: maven:3-jdk-8
  before_script:
  - "apt-get -qq -y install wget"
  - "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - "
  - "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'"
  - "apt-get -y update"
  - "apt-get -y install google-chrome-stable"

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn compile -X"
  artifacts:
    paths:
    - ui/target/*
    - api/target/*
    - gateway/target/*

maven-test:
  <<: *chrome_definition
  stage: test
  script:
  - export PATH=$PATH:ui/node
  - ui/node_modules/@angular/cli/bin/ng test --code-coverage=false --progress=false --watch=false --browsers=ChromeHeadlessCI
  - ui/node_modules/@angular/cli/bin/ng e2e

docker-build:
  <<: *chrome_definition
  stage: package
  script: "mvn package -X"

docker-install:
  stage: install
  before_script:
  - docker info
  script:
  - docker images

#  script:
#  - docker build -t tenentedan9/ui:$TAG ./ui
#  - docker build -t tenentedan9/gateway:$TAG ./gateway
#  - docker build -t tenentedan9/api:$TAG ./api
#  - docker login -u AWS -p $AWS_TOKEN https://$AWS_DOCKER_REGISTRY/
#  - docker tag tenentedan9/ui:$TAG $AWS_DOCKER_REGISTRY/ui:$TAG
#  - docker tag tenentedan9/gateway:$TAG $AWS_DOCKER_REGISTRY/gateway:$TAG
#  - docker tag tenentedan9/api:$TAG $AWS_DOCKER_REGISTRY/api:$TAG
#  - docker push $AWS_DOCKER_REGISTRY/ui:$TAG
#  - docker push $AWS_DOCKER_REGISTRY/gateway:$TAG
#  - docker push $AWS_DOCKER_REGISTRY/api:$TAG
