image: docker:latest
services:
 - docker

#variables:
#  DOCKER_DRIVER: overlay

stages:
- build
- test
- package

cache:
  paths:
  - ui/node
  - ui/node_modules

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn compile"
  artifacts:
    paths:
    - ui/target/*
    - api/target/*
    - gateway/target/*

maven-test:
  image: maven:3-jdk-8
  stage: test
  script: "mvn test"

docker-build:
  image: maven:3-jdk-8
  stage: package
  script: "mvn package"