image: docker:latest
services:
 - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker:2375
  TAG: 0.0.1-SNAPSHOT
  MAVEN_OPTS: "-Dmaven.repo.local=m2-repository"
#  BUILD_DEPENDENCY: target/dependency

stages:
- build
- test
- package

cache:
  paths:
  - ui/node
  - ui/node_modules
  - m2-repository
#  - ui/target/
#  - gateway/target/
#  - api/target/

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn compile"
  artifacts:
    paths:
    - ui/target/*
    - api/target/*
    - gateway/target/*

#maven-test:
#  image: maven:3-jdk-8
#  stage: test
#  script: "mvn test"
#
#docker-build:
#  stage: package
#  before_script:
#  - docker info
#  script:
#  - docker build -t tenentedan9/ui:$TAG ./ui
#  - docker build -t tenentedan9/gateway:$TAG ./gateway
#  - docker build -t tenentedan9/api:$TAG ./api
#  - docker login -u AWS -p $AWS_TOKEN https://$AWS_DOCKER_REGISTRY/
#  - docker tag tenentedan9/ui:$TAG $AWS_DOCKER_REGISTRY/ui:$TAG
#  - docker tag tenentedan9/gateway:$TAG $AWS_DOCKER_REGISTRY/gateway:$TAG
#  - docker tag tenentedan9/api:$TAG $AWS_DOCKER_REGISTRY/api:$TAG
#  - docker push $AWS_DOCKER_REGISTRY/ui:$TAG
#  - docker push $AWS_DOCKER_REGISTRY/gateway:$TAG
#  - docker push $AWS_DOCKER_REGISTRY/api:$TAG
