image: docker:latest
services:
 - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker:2375

stages:
- build
- test
- package

cache:
  paths:
  - ui/node
  - ui/node_modules

before_script:
  - "apt-get -qq -y install wget"
  - "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - "
  - "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'"
  - "apt-get -y update"
  - "apt-get -y install google-chrome-stable"

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn compile"
  artifacts:
    paths:
    - ui/target/*
    - api/target/*
    - gateway/target/*

maven-test:
  image: maven:3-jdk-8
  stage: test
  script: "mvn test -Dmaven.compile.skip=true"
  artifacts:
    paths:
    - ui/target/*
    - api/target/*
    - gateway/target/*


docker-build:
  image: maven:3-jdk-8
  stage: package
  script: "mvn package -Dmaven.compile.skip=true -Dmaven.test.skip=true"
  artifacts:
    paths:
    - ui/target/*
    - api/target/*
    - gateway/target/*
