dist: trusty
sudo: false

language: java
jdk:
- openjdk8

services:
- docker

env:
  global:
#  - TAG=0.0.1-SNAPSHOT
  - MAVEN_OPTS="-Dmaven.repo.local=.m2"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
  - ./ui/node_modules
  - ./ui/node
  - ./.m2/
before_cache:
- echo "listing cache directories"
- ls -la

before_install:
- pip install --user awscli

install: true

script:
  - mvn package -B
#  - eval $(aws ecr get-login --no-include-email --region eu-central-1)
#  - docker tag tenentedan9/app:$TAG $AWS_REGISTRY/app:$TAG
#  - docker push $AWS_REGISTRY/app:$TAG

notifications:
  email: false