dist: xenial
sudo: required

language: java
jdk:
- openjdk8

services:
  - docker

env:
  global:
    - TAG="0.0.1-SNAPSHOT"
    - IMAGE="app"
    - DOCKER_USER="tenentedan9"
    - AWS_DEFAULT_REGION="eu-central-1"
    - MAVEN_OPTS="-Dmaven.repo.local=.m2"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./app/node_modules
    - ./app/node
    - ./.m2/

install: bash .travis/install.sh

script: bash .travis/script.sh

deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true

after_deploy: bash .travis/after_deploy.sh


notifications:
  email: false