dist: trusty
sudo: false

language: node_js
node_js:
- "9.11"

services:
  - docker

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
  - ./node_modules


install:
- mvn install

script:
- mvn test