dist: xenial
sudo: required

language: java
jdk:
- openjdk8

services:
  - docker

env:
  global:
    - TAG="0.0.1-SNAPSHOT"
    - IMAGE="app"
    - DOCKER_USER="tenentedan9"
    - AWS_DEFAULT_REGION="eu-central-1"
    - MAVEN_OPTS="-Dmaven.repo.local=.m2"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  snaps:
    - name: aws-cli
      classic: true
      channel: latest/edge

cache:
  directories:
    - ./app/node_modules
    - ./app/node
    - ./.m2/

before_install:
  - sudo apt-get autoremove -y

install: true

script:
  - chmod +x travis_scripts/travis_install.sh
  - sh travis_scripts/travis_install.sh

notifications:
  email: false