dist: trusty
sudo: false

services:
- docker

env:
  global:
# - DOCKER_DRIVER=overlay
# - DOCKER_HOST=tcp://docker:2375
  - MAVEN_OPTS="-Dmaven.repo.local=.m2"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
  - ./ui/node_modules
  - ./ui/node
  - ./.m2/

test:
  - echo "fake test"

install:
  - mvn package
  - docker images
  - docker login -u AWS -p $AWS_REGISTRY_TOKEN $AWS_REGISTRY
  - docker tag tenentedan9/ui:$TAG $AWS_REGISTRY/ui:$TAG
  - docker tag tenentedan9/gateway:$TAG $AWS_REGISTRY/gateway:$TAG
  - docker tag tenentedan9/api:$TAG $AWS_REGISTRY/api:$TAG
  - docker push $AWS_REGISTRY/ui:$TAG
  - docker push $AWS_REGISTRY/gateway:$TAG
  - docker push $AWS_REGISTRY/api:$TAG
