dist: xenial
sudo: required

language: java
jdk:
- openjdk8

services:
  - docker

env:
  global:
    - TAG="0.0.1-SNAPSHOT"
    - DOCKER_USER="tenentedan9"
    - AWS_DEFAULT_REGION="eu-central-1"
    - MAVEN_OPTS="-Dmaven.repo.local=.m2"
    - TF_VERSION="0.13.5"
    - MVN_VERSION="3.6.1"
    - TESTCONTAINERS_RYUK_DISABLED=true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./web/node_modules
    - ./web/node
    - ./.m2/

before_install:
  - export M2_HOME="$PWD/apache-maven-${MVN_VERSION}"
  - export PATH="$M2_HOME/bin:$PATH"

install: bash .travis/install.sh

script:
  - ./terraform validate
  - bash .travis/script.sh


deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true

after_deploy:
  - bash .travis/push_images.sh -i="app" -t=$TAG -r=$AWS_DEFAULT_REGION -u=$DOCKER_USER
  - bash .travis/push_images.sh -i="web" -t=$TAG -r=$AWS_DEFAULT_REGION -u=$DOCKER_USER
  - bash .travis/taint_deploy.sh

after_success: bash .travis/after_success.sh

notifications:
  email: false
