dist: trusty
sudo: false

language: node_js
node_js:
- "9.11"

services:
- docker

env:
  global:
# - DOCKER_DRIVER=overlay
# - DOCKER_HOST=tcp://docker:2375
  - MAVEN_OPTS="-Dmaven.repo.local=.m2"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
  - .ui/node_modules
  - .ui/node
  - .m2/

install:
  - mvn package
  - docker images