dist: trusty
sudo: false

language: node_js
node_js:
- "9.11"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
  - ./node_modules

install:
- mvn clean install

script:
- mvn test