version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
    - /data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: crm
      POSTGRES_PASSWORD: daniel
      POSTGRES_USER: daniel
      PGDATA: /var/lib/postgresql/data/pgdata
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.hostname == data
    networks:
      - overall
  redis:
    container_name: redis
    image: redis
    volumes:
    - /data/redis:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.hostname == data
    networks:
      - overall
  app:
    container_name: app
    image: 359080832247.dkr.ecr.eu-central-1.amazonaws.com/app:0.0.1-SNAPSHOT
    ports:
    - 80:9000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: daniel
      POSTGRES_USER: daniel
      REDIS_PORT: 6379
      REDIS_HOST: redis
      BASE_HOST: http://www.goodfellas.fitness
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - overall
networks:
  overall: