version: "3"

services:
  postgres:
    image: postgres
    volumes:
    - /data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: crm
      POSTGRES_PASSWORD: password#
      POSTGRES_USER: goodfellas
      PGDATA: /var/lib/postgresql/data/pgdata
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.hostname == ip-10-0-0-79
    networks:
      - overall
  redis:
    image: redis
    volumes:
    - /data/redis:/data
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.hostname == ip-10-0-0-79
    networks:
      - overall
  app:
    image: 359080832247.dkr.ecr.eu-central-1.amazonaws.com/app:0.0.1-SNAPSHOT
    ports:
      - 443:8443
      - 80:8080
    environment:
      POSTGRES_HOST:  postgres
      POSTGRES_PASSWORD: password#
      POSTGRES_USER: goodfellas
      REDIS_PORT: 6379
      REDIS_HOST: redis
      BASE_HOST: https://www.goodfellas.fitness
    volumes:
      - ~/certs/AA22E6508A15A5F3C2425B7E6A9CF604.txt:/app/META-INF/resources/.well-known/pki-validation/AA22E6508A15A5F3C2425B7E6A9CF604.txt
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ip-10-0-0-98
    networks:
    - overall
networks:
  overall: