
# ------------------------------
# BUSINESS CONFIGURATION
# ------------------------------
baseUrl: http://localhost
reservationBeforeHours: 6

logging:
  level:
    org.springframework.security: INFO

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: trainingoodfellas@gmail.com
    password: training#
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  datasource:
    url: jdbc:postgresql://postgres:5432/crm
    username: daniel
    password: daniel
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: resource
  session.store-type: redis
  redis:
    host: redis
    port: 6379
server:
  port: 9000