spring:
  profiles:
    active: prod
  application:
    name: app
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  data:
    redis:
      repositories:
        enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: trainingoodfellas@gmail.com
    password: training#
    properties.mail.smtp:
      auth: true
      starttls.enable: true

server:
  servlet.session.timeout: 60s
  port: 9000

reservationBeforeHours: 6

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/crm
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security: ERROR

baseUrl: ${BASE_HOST}

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: daniel
    password: daniel
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.springframework.security: INFO

baseUrl: http://localhost

