spring:
  profiles:
    active: prod
  application:
    name: app
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache.redis.time-to-live: 86400000
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    redis:
      repositories:
        enabled: false
  main:
    banner-mode: off

server:
  port: 80
  use-forward-headers: true
  servlet.context-path: /api

management:
  health:
    mail:
      enabled: false

baseUrl: ${BASE_HOST}
adminEmail: ${ADMIN_EMAIL}
adminPassword: ${ADMIN_PASSWORD}
schema: ${APP_NAME}


---

spring:
  profiles: prod

logging:
  level:
    root: info
    org.springframework.beans: off
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.http: info
    org.flywaydb: info
    it.gym: info

---

spring:
  profiles: dev

logging:
  level:
    root: info
    org.springframework.beans: off
    org.springframework.web: debug
    it.gym: debug
    it.gym.config.ApiLoggerInterceptor: off
