spring:
  profiles:
    active: prod
  application:
    name: app
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

logging:
  level:
    root: info
    org.springframework.beans: off
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.http: info
    org.flywaydb: info
    it.gym: info

server:
  port: 80
  use-forward-headers: true
  servlet.context-path: /api

management:
  health:
    mail:
      enabled: false

baseUrl: ${BASE_HOST}
admin_email: ${ADMIN_EMAIL}
admin_password: ${ADMIN_PASSWORD}
schema: ${APP_NAME}


---

spring:
  profiles: prod
---

spring:
  profiles: dev

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.http: debug
    org.flywaydb: debug
    it.gym: debug
