spring:
  profiles:
    active: prod
  application:
    name: app
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/crm
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  redis:
    host: ${REDIS_HOST}
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: trainingoodfellas@gmail.com
    password: ${GMAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

baseUrl: ${BASE_HOST}
reservationBeforeHours: 6

server:
  port: 80

---

spring:
  profiles: prod

  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security: ERROR

---

spring:
  profiles: dev
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG


